### ISSUE TITLE
Copy-Paste error for class HashCodeRouteCriterion, attribute name : 

### ISSUE THREAD

**Issue by PhilippeGalvan** [garciparedes/jinete#100]
# Bug Report Details

## Description

I think there is a naming error in the class HashCodeRouteCriterion for the super attribute `name`: 
```
class HashCodeRouteCriterion(RouteCriterion):

    def __init__(self, *args, **kwargs):
        super().__init__(
            direction=OptimizationDirection.MAXIMIZATION,
            name='Longest-Time',
            *args, **kwargs,
        )
```
In my opinion, it should be : ```name='Hash-Code'```.instead of ```name='Longest-Time'```

**Comment by garciparedes** [comment]
You're right @PhilippeGalvan Thank you so much for detecting that copy-pasting error 😉
