### ISSUE TITLE
A pick-up point followed by delivery point

### ISSUE THREAD

**Issue by osdsanaa** [garciparedes/jinete#132]
# Feature Request Details

## Use Case
I have noticed that you suppose in your work that each pickup point is directly followed by a delivery point
## Solution Proposal
Normally a set of points can be picked up as long as the capacity of the vehicle is not exceded.

**Comment by garciparedes** [comment]
Hi @osdsanaa,

Yes! the current implementation is designed to solve the Dial-a-Ride Problem (DARP). As you can see on [this](https://www.researchgate.net/publication/220462650_The_dial-a-ride_problem_DARP_Models_and_algorithms), it is composed of pickups and deliveries in a way that to satisfy the a delivery, you must first satisfy the corresponding pickup. 

There are other related problems such us the Vehicle Routing Problem (VRP) in which every points are equal (or at least not hardly dependent between them), but the DARP imposes that constraints to the formulation. 

I think it would be an interesting feature to implement that kind of problems also over `jinete`! 🙂

**Comment by osdsanaa** [comment]
Hi @garciparedes,
Even with Dial a ride problem, I'm not talking about the constraint of precedence.
But when I tested @jinete on data from Cordeau the result was that you can't serve a request without delivering the previous request. which increases the cost of the route.

**Comment by garciparedes** [comment]
Could you include your here your launching script? I've executed [this one](https://github.com/garciparedes/jinete/blob/master/examples/cordeau/example_grasp.py) right now and it works as expected (taking into account the vehicle capacity constrains at each step).

**Comment by garciparedes** [comment]
As you can see in the following generated plot, there are contiguous pickup stops (shown as points identified with positive integers) and contiguous deliveries (shown as points identified with negative integers)

![image](https://user-images.githubusercontent.com/5640366/98982199-45c9d080-251f-11eb-9bab-70f4fbe31fb8.png)

**Comment by osdsanaa** [comment]
Sorry, I think I missed something in the first test. It's clear now, you solved the dynamic version of the problem?

**Comment by garciparedes** [comment]
Hi @osdsanaa!

Nop, the problem I'm solving in this case is the static one as I assume I know the full set of trips to be planned before starting the algorithm execution. In the dynamic version, the set of trips are not entirely known before starting to solve the problem 

In the dynamic version each trip is received at a random time and the algorithm should be able to recompute a new planning based on the previous one, but taking into account the trips that have been already complete. 

I planned to implement a new `jinete.Dispatcher` subclass (something like `jinete.DynamicDispatcher`) to solve that kind of problems.
