### ISSUE TITLE
Missing Pipfile and Pipfile.lock

### ISSUE THREAD

**Issue by PhilippeGalvan** [garciparedes/jinete#92]
# Bug Report Details

## Description
Pipfile and Pipfile.lock files are missing thus imports are not made when running :
```bash
pipenv install --dev
```

Note : pipenv is pretty new for me, I'm still working with pip and venv separately but from my understanding Pipfile and Pipfile.lock are the equivalent of requirements for pip and thus should be shared between contributors. 

## Expected behavior

Add Pipfile and Pipfile.lock on remote repository.

**Comment by garciparedes** [comment]
As said in #91, I'll close this issue and continue the discussion in the other issue.
