### ISSUE TITLE
Include "identifier" on "Service" objects

### ISSUE THREAD

**Issue by garciparedes** [garciparedes/jinete#97]
# Feature Request Details

## Use Case

Currently, the service objects does not have any identifier, which is present in common imput problem formats. It would be interesting to include it in the object to ease results understanding.

## Solution Proposal
 
* Include `identifier` attribute on `Service` class as `str` using a generated uuid as default value.
* Modify current `LoaderFormatter` implementations to inject this attribute.

**Comment by garciparedes** [comment]
Hi @PhilippeGalvan!

First of all, thanks again for your contribution in the project. Probably I need to improve my explanation about the integration with `LoaderFormatter` implementations (I'll start working on the documentation with this part). 

In short, `jinete` has a concept of `Loader` as the entity which has the responsibility to create the needed objets (from a plain text file right now) to perform the optimization. In the same way, the `Storer` entity is the responsible to export the solution (as a plaint text file right now). To take into account of different file formats the `LoaderFormatter` and `StorerFormatter` concepts was created and their responsibility is to "load" and "dumps" the data from/to raw formats to `jinete`'s models.

The main reason why I proposed to include the `identifier` attribute on the `Service` entity (understanding service as the task to pickup or deliver something at some destination) is to improve the understanding of the final results. 

Then, it is necessary to "connect" the changes at `Service` to its current uses:
* In `CordeauLaporteLoaderFormatter` setting the `'0'` identifier  to depot service, the corresponing `origin_idx` to the pickup service and the `destination_idx` to the delivery service.
* In `HashCodeLoaderFormatter` setting the `'0'` identifier  to depot service, the corresponing `f'+{identifier}'` to the pickup service and the `f'-{identifier}'` to the delivery service.

I think that applying this changes the ease to track each `Service` should be much more easier. 🙂

**Comment by PhilippeGalvan** [comment]
Hi @garciparedes!

Thank you for your explanations, it's a pleasure to contribute to a project with an already clean and well structured backbone !

I understand the global idea but I don't fully understand which part of the model does what and I'm not against a brief explanation of the purpose and nteractions between (services, stops, routes, vehicles, surface, trips, positions, plannings and planned_trips)! Nevertheless, I do realize that I will understand with time and it will be explicited in future documentation :)

Reading the code and guessing, I would add : 
```python
    @abstractmethod
    def service(self, surface : Surface, *args, **kwargs) -> Service:
        pass
```
to `LoaderFormatter` because of the `build_trip` method calling `Surface` to create a `Service` 

About the format of input data, I'm not sure what it would look like in a file.

**Comment by garciparedes** [comment]
Hi @PhilippeGalvan !

I understand you, the project documentation is practically inexistent right now. I'll dedicate much more effort in this part, especially now that I'm not alone. 🙂 

I'm thinking to include an entity-relationship diagram in the documentation to explain well the model structure and meaning around the library. Also, I'll provide a docstring description about every model and how it is related with the remaining ones. (I created the #101 issue to resolve that, so you're invited to comment any mis-explained term in the documentation)

**Comment by garciparedes** [comment]
About your proposal, I think an auxiliar method is necessary to clarify the code, but I wouldn't create in this way. Possibly I would include a `_build_service(...) -> Service` method, but not in the same way as `job(...) -> Job`, `fleet(...) -> Fleet` or `surface(...) -> Surface` because those returning values will be one instance objects on the `LoaderFormatter`. On the opposite, vehicles, trips, services, etc. won't be one instance objects. 

Probably, you'll understand me better when I resolve the #101 issue!
