### ISSUE TITLE
Zsh pip install not properly working

### ISSUE THREAD

**Issue by PhilippeGalvan** [garciparedes/jinete#98]
# Bug Report Details

## Description

```bash
pip install -e .[all]
```
command in :file:`Readme.md` is not working with zsh.
See : https://stackoverflow.com/a/55063830/10810425

### Environment

python 3.7
fedora 30

### Steps

```bash
pip install -e .[all]
```

### In `Readme.md`:
For zsh users : 
```bash
pip install -e ".[all]"
```

**Comment by garciparedes** [comment]
As the proposed changes works properly both for `zsh` and for `bash` shells, I think is a good idea to change it in the documentation. Thanks @PhilippeGalvan !
